### ISSUE TITLE
Is there code for visualization of the MTMC tracking result in this repo?

### ISSUE THREAD

**Issue by sisrfeng** [hou-yz/DeepCC_hou#3]

**Comment by hou-yz** [comment]
Yes, there are multiple visualizations created by Ergys, e.g. [link](https://github.com/hou-yz/DeepCC-local/blob/d280f0aa0cee60fe30da07e5a62b55ec344da4c2/src/visualization/render_results.m#L1). 

go under /src/visualization for all visualizations.
