### ISSUE TITLE
File to run demo for test in AIC19?

### ISSUE THREAD

**Issue by elun15** [hou-yz/DeepCC_hou#4]
Hello, 
I want to run the demo for the test set in AIC19 challenge, however, the file _test_aic_ensemble.m_ does not exist in the repo. It only appears _test_aic_zju_ensemble.m_, should I run this one? What's the difference between these two files? I want to replicate the results obtained in the 2019 challenge. 

Thank you in advance

**Comment by hou-yz** [comment]
Hi,

Thank you for your interest. 
Sorry for the invalid reference for the test script. It should be _test_aic_zju_ensemble.m_ instead. 

Best,
Yunzhong
