### ISSUE TITLE
Problems to run the code

### ISSUE THREAD

**Issue by borre47** [hou-yz/DeepCC_hou#7]
Hi, where can i get the missing files? For example: "AIC_ensemble/gt_10fps/model_param_L2_50.mat"
Thanks in advance

**Comment by hou-yz** [comment]
Hi,
Please first extract your own set of re-id features for all the detections, and then the tracker should be able to run.
As for the file you mentioned, it is a saved MLP model for matlab from LAAM https://github.com/hou-yz/DeepCC-local/tree/master/src/hyper_score. please see the paper for details. you can also train it yourself once you have the re-id features.
Best,
Yunzhong
